apiVersion: v1
kind: Pod
metadata:
  name: booking-service-pod
  namespace: kanwalnainsingh
  labels:
    app: booking-service
spec:
  restartPolicy: Never
  volumes:
    - name: shared-data
      emptyDir: {}

  containers:
    - name: booking-service-container
      ports:
      - containerPort: 8081
      image: kanwalnainsingh/opendesk-booking-service:latest
      args: ["java","-cp","app:app/lib/*","github.opendesk.bookingservice.BookingServiceApplication"]
      volumeMounts:
        - name: shared-data
          mountPath: /tmp

    - name: redis-container
      image: redis
      ports:
        - containerPort: 6379
      volumeMounts:
        - name: shared-data
          mountPath: /tmp